[package]
name = "dungeon"
version = "0.1.0"
authors = ["Zack Porter <zack@zackporter.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egaku2d = "0.5.2"
axgeom = "1.6.5"
rand = "0.5.5"
